import JSZip from "jszip";
import { PROJECT_FILES, README } from "./projectFiles";

export const ZIP_NAME = "pearl-dental-source.zip";
const ROOT_FOLDER = "pearl-dental";

/* ------------------------------------------------------------------ */
/*  Building                                                          */
/* ------------------------------------------------------------------ */

/**
 * Builds the complete source archive as an in-memory Blob.
 * node_modules and the lockfile are intentionally excluded — both are
 * regenerated by `npm install`.
 */
export async function createSourceZipBlob(): Promise<Blob> {
  const zip = new JSZip();
  const root = zip.folder(ROOT_FOLDER);
  if (!root) throw new Error("Could not create zip folder");

  root.file("README.md", README);
  for (const file of PROJECT_FILES) {
    root.file(file.path, file.content);
  }

  return zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 7 },
  });
}

/* ------------------------------------------------------------------ */
/*  Verification — prove the archive is real, not a placeholder       */
/* ------------------------------------------------------------------ */

/** Ensures the bundled manifest actually carries source text. */
export function validateManifest(): { files: number; ok: boolean } {
  const empty = PROJECT_FILES.filter((f) => f.content.trim().length === 0);
  return { files: PROJECT_FILES.length, ok: empty.length === 0 };
}

/**
 * Reads the generated archive back with JSZip and confirms that
 * README.md and every manifest file are present and non-empty.
 */
export async function verifySourceZip(
  blob: Blob
): Promise<{ entries: number; hasReadme: boolean; totalBytes: number }> {
  const zip = await JSZip.loadAsync(blob);
  const prefix = `${ROOT_FOLDER}/`;
  let totalBytes = 0;
  let hasReadme = false;
  const seen = new Set<string>();

  zip.forEach((relativePath, entry) => {
    if (entry.dir) return;
    const path = relativePath.startsWith(prefix)
      ? relativePath.slice(prefix.length)
      : relativePath;
    seen.add(path);
    if (path === "README.md") hasReadme = true;
  });

  for (const name of seen) {
    const entry = zip.file(`${prefix}${name}`);
    if (entry) {
      const text = await entry.async("string");
      totalBytes += text.length;
    }
  }

  const missing = PROJECT_FILES.filter((f) => !seen.has(f.path));
  if (!hasReadme) throw new Error("README.md missing from archive");
  if (missing.length > 0) {
    throw new Error(`Missing from archive: ${missing.map((f) => f.path).join(", ")}`);
  }

  return { entries: seen.size, hasReadme, totalBytes };
}

/* ------------------------------------------------------------------ */
/*  Delivery strategies                                               */
/* ------------------------------------------------------------------ */

export function isInIframe(): boolean {
  try {
    return window.self !== window.top;
  } catch {
    // Cross-origin access to `top` throws — that also means we're framed.
    return true;
  }
}

const scheduleRevoke = (url: string, ms = 60_000) =>
  window.setTimeout(() => URL.revokeObjectURL(url), ms);

export type DownloadMethod = "top-frame" | "anchor";

/**
 * Primary strategy: a user-clicked save.
 * 1) If the preview host is same-origin, create the anchor in the
 *    TOP-LEVEL document — top-level downloads are never sandboxed.
 * 2) Otherwise fall back to an anchor in the current document.
 * Both rely on a blob object URL, which is the direct-browser
 * mechanism (no server endpoint required).
 */
export function triggerAnchorDownload(url: string): DownloadMethod {
  try {
    const top = window.top;
    if (top && top !== window.self) {
      const doc = top.document;
      const a = doc.createElement("a");
      a.href = url;
      a.download = ZIP_NAME;
      doc.body.appendChild(a);
      a.click();
      a.remove();
      scheduleRevoke(url);
      return "top-frame";
    }
  } catch {
    // Cross-origin top frame — use the current document instead.
  }

  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = ZIP_NAME;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  scheduleRevoke(url);
  return "anchor";
}

/**
 * Escape hatch: open the blob in a NEW top-level tab. The new tab is a
 * top-level browsing context, so it is not subject to the preview
 * iframe's download sandbox — Chrome downloads the zip there.
 * Returns false if the popup was blocked.
 */
export function openZipInNewTab(url: string): boolean {
  const win = window.open(url, "_blank");
  return win !== null;
}

/** The whole source tree as one marked-up text block. */
export function buildSourceText(): string {
  const parts: string[] = [
    "PEARL DENTAL & AESTHETICS — COMPLETE PROJECT SOURCE",
    `${PROJECT_FILES.length + 1} files. Split on the "=== FILE: …" markers to restore the tree.`,
    "",
    "=== FILE: README.md ===",
    README,
  ];
  for (const file of PROJECT_FILES) {
    parts.push("", `=== FILE: ${file.path} ===`, file.content);
  }
  return parts.join("\n");
}

/* ------------------------------------------------------------------ */
/*  File System Access — the native "Save As" dialog.                 */
/*  Bypasses the download sandbox entirely: no anchor click, no       */
/*  blob-URL navigation, no popup. Chrome/Edge on desktop.            */
/* ------------------------------------------------------------------ */

type WritableStreamLike = {
  write: (data: Blob) => Promise<void>;
  close: () => Promise<void>;
};
type FileHandleLike = {
  createWritable: () => Promise<WritableStreamLike>;
};
type SaveFilePickerLike = (options: {
  suggestedName: string;
  types: { description: string; accept: Record<string, string[]> }[];
}) => Promise<FileHandleLike>;

export type SaveResult = "saved" | "unsupported" | "cancelled";

/**
 * Opens the OS file picker and streams the blob to disk.
 * Returns "unsupported" where the API doesn't exist so callers can
 * fall through to other delivery methods.
 */
export async function saveViaFileSystemAccess(blob: Blob): Promise<SaveResult> {
  const picker = (
    window as Window & { showSaveFilePicker?: SaveFilePickerLike }
  ).showSaveFilePicker;
  if (typeof picker !== "function") return "unsupported";

  try {
    const handle = await picker.call(window, {
      suggestedName: ZIP_NAME,
      types: [{ description: "ZIP archive", accept: { "application/zip": [".zip"] } }],
    });
    const writable = await handle.createWritable();
    await writable.write(blob);
    await writable.close();
    return "saved";
  } catch (err) {
    if (err instanceof DOMException && err.name === "AbortError") return "cancelled";
    return "unsupported";
  }
}

/**
 * Copies the entire source tree to the clipboard — the fallback for
 * environments where every download path is blocked.
 */
export async function copyAllSource(): Promise<void> {
  const text = buildSourceText();

  if (navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return;
    } catch {
      // Permission denied — fall through to the legacy path.
    }
  }
  const area = document.createElement("textarea");
  area.value = text;
  area.style.position = "fixed";
  area.style.opacity = "0";
  document.body.appendChild(area);
  area.select();
  const ok = document.execCommand("copy");
  area.remove();
  if (!ok) throw new Error("Clipboard unavailable");
}

/* ------------------------------------------------------------------ */
/*  Formatting helpers                                                */
/* ------------------------------------------------------------------ */

export const totalSourceBytes = PROJECT_FILES.reduce(
  (sum, f) => sum + f.content.length,
  0
);

export const formatKb = (bytes: number) => `${(bytes / 1024).toFixed(1)} KB`;
