import JSZip from "jszip";
import { PROJECT_FILES, README } from "./projectFiles";

export const ZIP_NAME = "pearl-dental-source.zip";
const ROOT_FOLDER = "pearl-dental";

/**
 * Builds the complete source archive as an in-memory Blob.
 * Node modules and the lockfile are intentionally excluded —
 * both are regenerated by `npm install`.
 */
export async function createSourceZipBlob(): Promise<Blob> {
  const zip = new JSZip();
  const root = zip.folder(ROOT_FOLDER);
  if (!root) throw new Error("Could not create zip folder");

  root.file("README.md", README);
  for (const file of PROJECT_FILES) {
    root.file(file.path, file.content);
  }

  return zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 7 },
  });
}

/**
 * Programmatic download — works in regular browser tabs, but can be
 * silently blocked inside sandboxed preview iframes. The Download page
 * therefore prefers a real user-clicked <a download> anchor and offers
 * a copy-to-clipboard fallback on top.
 */
export async function downloadProjectZip(): Promise<void> {
  const blob = await createSourceZipBlob();
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = ZIP_NAME;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 4000);
}

/**
 * Fallback for environments where file downloads are blocked:
 * copies the entire source tree as a single marked-up text block.
 */
export async function copyAllSource(): Promise<void> {
  const parts: string[] = [
    "PEARL DENTAL & AESTHETICS — COMPLETE PROJECT SOURCE",
    `${PROJECT_FILES.length + 1} files. Split on the "=== FILE: …" markers to restore the tree.`,
    "",
    "=== FILE: README.md ===",
    README,
  ];
  for (const file of PROJECT_FILES) {
    parts.push("", `=== FILE: ${file.path} ===`, file.content);
  }
  const text = parts.join("\n");

  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  // Legacy fallback — works in most sandboxed iframes too.
  const area = document.createElement("textarea");
  area.value = text;
  area.style.position = "fixed";
  area.style.opacity = "0";
  document.body.appendChild(area);
  area.select();
  const ok = document.execCommand("copy");
  area.remove();
  if (!ok) throw new Error("Clipboard unavailable");
}

export const totalSourceBytes = PROJECT_FILES.reduce(
  (sum, f) => sum + f.content.length,
  0
);

export const formatKb = (bytes: number) => `${(bytes / 1024).toFixed(1)} KB`;
