import JSZip from "jszip";
import { PROJECT_FILES, README } from "./projectFiles";

const ZIP_NAME = "pearl-dental-source.zip";
const ROOT_FOLDER = "pearl-dental";

/**
 * Packages the entire project source into a zip archive in the browser
 * and triggers a download. Node modules and the lockfile are intentionally
 * excluded — both are regenerated by `npm install`.
 */
export async function downloadProjectZip(): Promise<void> {
  const zip = new JSZip();
  const root = zip.folder(ROOT_FOLDER);
  if (!root) throw new Error("Could not create zip folder");

  root.file("README.md", README);
  for (const file of PROJECT_FILES) {
    root.file(file.path, file.content);
  }

  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 7 },
  });

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = ZIP_NAME;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export const totalSourceBytes = PROJECT_FILES.reduce(
  (sum, f) => sum + f.content.length,
  0
);

export const formatKb = (bytes: number) => `${(bytes / 1024).toFixed(1)} KB`;
